name: CI
on: workflow_call

defaults:
  run:
    shell: bash

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 🎨 Run prettier
        run: yarn ci:prettier

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 🧹 Run eslint
        run: yarn ci:eslint

  typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 🎨 Run typescript compiler (tsc)
        run: yarn ci:tsc

  plugin-integrity:
    name: plugin integrity
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 🔌 Check config plugin order
        run: yarn ci:check-plugin-integrity

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 🕵️‍♀️  Run tests
        run: yarn test

  expo-doctor:
    name: Expo Doctor
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
      - name: 👩‍⚕️ Expo Doctor
        run: EXPO_DOCTOR_SKIP_DEPENDENCY_VERSION_CHECK=1 npx expo-doctor@latest
